[workspace]

members = [
    "day3/24_traits",
    "day3/25_important_traits",
    "day3/26_exercise",
    "day3/27_error_handling",
    "day3/28_testing",
    "day3/29_unsafe_rust",
    "day3/30_exercise",
    "day4/32_concurrency",
]