[package]
name = "standard_library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day2_box"
path = "src/box.rs"

[[bin]]
name = "day2_rc"
path = "src/rc.rs"

[dependencies]
