[package]
name = "memory_management"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day1_stack_memory"
path = "src/stack_memory.rs"

[dependencies]
